org: kloughead
app: serverless-proxy
service: serverless-proxy
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    API_KEY: ${env:API_KEY}
  httpApi:
    cors:
      allowedOrigins:
        - http://example.com # replace with your domain(s)
        - http://localhost:3001
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
      allowCredentials: true
      exposedResponseHeaders:
        - Special-Response-Header
      maxAge: 6000 # In seconds

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
